# Generated by Django 2.2.7 on 2020-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParseInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='解析名称')),
                ('domin', models.CharField(max_length=128, verbose_name='解析域名')),
                ('parse_url', models.CharField(max_length=512, verbose_name='解析链接')),
                ('status', models.PositiveIntegerField(choices=[(1, '有效地址'), (0, '无效地址')], default=1, verbose_name='是否有效')),
                ('speed', models.PositiveIntegerField(default=1, verbose_name='解析速度')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '解析接口',
                'verbose_name_plural': '解析接口',
            },
        ),
    ]
