# Generated by Django 2.2.7 on 2020-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='email',
            field=models.EmailField(default=1, max_length=512, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
