# Generated by Django 2.2.7 on 2020-01-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domin', models.CharField(max_length=128, verbose_name='来源域名')),
                ('name', models.CharField(max_length=128, verbose_name='来源名称')),
                ('type', models.PositiveIntegerField(choices=[(1, '资源类'), (0, '解析类')], default=1, verbose_name='来源类型')),
                ('is_effect', models.PositiveIntegerField(choices=[(1, '有效地址'), (0, '无效地址')], default=1, verbose_name='是否有效')),
                ('format_page', models.CharField(max_length=512, verbose_name='构造初始爬取页链接')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '来源',
                'verbose_name_plural': '来源',
            },
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512, verbose_name='视频名称')),
                ('alias', models.CharField(db_index=True, max_length=512, verbose_name='别名')),
                ('cover_url', models.CharField(max_length=512, verbose_name='封面链接')),
                ('director', models.CharField(max_length=512, verbose_name='导演')),
                ('actor', models.CharField(max_length=1024, verbose_name='演员')),
                ('first_type', models.CharField(max_length=256, verbose_name='视频类别1')),
                ('second_type', models.CharField(max_length=256, verbose_name='视频类别2')),
                ('region', models.CharField(max_length=256, verbose_name='地区')),
                ('update_time', models.CharField(max_length=128, verbose_name='资源更新时间')),
                ('nums', models.PositiveIntegerField(default=1, verbose_name='总集数')),
                ('release_time', models.CharField(db_index=True, max_length=64, verbose_name='上映年份')),
                ('intro', models.TextField(verbose_name='简介')),
                ('source', models.CharField(max_length=128, verbose_name='来源网站名称')),
                ('created_time', models.CharField(max_length=128, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '视频信息',
                'verbose_name_plural': '视频信息',
            },
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='视频名称')),
                ('link', models.CharField(db_index=True, max_length=512, verbose_name='视频链接')),
                ('number', models.CharField(max_length=128, verbose_name='当前视频集数')),
                ('is_new', models.PositiveIntegerField(choices=[(1, '最新一集'), (0, '非最新一集')], default=0, verbose_name='是否最新一集')),
                ('status', models.PositiveIntegerField(choices=[(1, '有效链接'), (0, '无效链接')], default=1, verbose_name='是否有效链接')),
                ('source', models.CharField(max_length=128, verbose_name='来源网站名称')),
                ('created_time', models.CharField(max_length=128, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '视频播放链接',
                'verbose_name_plural': '视频播放链接',
            },
        ),
        migrations.CreateModel(
            name='VideoPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='视频名称')),
                ('pv', models.PositiveIntegerField(default=1, verbose_name='页面访问量')),
                ('uv', models.PositiveIntegerField(default=1, verbose_name='独立访客数')),
            ],
            options={
                'verbose_name': '视频点击量',
                'verbose_name_plural': '视频点击量',
            },
        ),
    ]
