# Generated by Django 2.2.7 on 2020-01-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='remark',
            field=models.CharField(default='remark', max_length=512, verbose_name='视频备注'),
            preserve_default=False,
        ),
    ]
