# Generated by Django 2.2.7 on 2020-01-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_videoinfo_remark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPU',
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='pv',
            field=models.PositiveIntegerField(default=1, verbose_name='页面访问量'),
        ),
        migrations.AddField(
            model_name='videoinfo',
            name='uv',
            field=models.PositiveIntegerField(default=1, verbose_name='独立访客数'),
        ),
    ]
