# Generated by Django 2.2.7 on 2020-01-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20200113_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoinfo',
            name='pv',
        ),
        migrations.RemoveField(
            model_name='videoinfo',
            name='uv',
        ),
    ]
